### ISSUE TITLE
Guzzle, PHP HTTP client conflict

### ISSUE THREAD

**Issue by deepslam** [j0k3r/graby#108]
Hello!

I have a problem.
I'm trying to install this package - https://github.com/artesaos/laravel-linkedin but the package requires https://github.com/guzzle/guzzle 6.1.x version.
But your perfect (it's not irony!) package is blocking installation because requires an old version of Guzzle, PHP HTTP client.

Could you fix it, please?

And thank you for the great package!

Sincerely, Dmitry.

**Comment by j0k3r** [comment]
This should be fixed when this issue will be resolved: https://github.com/j0k3r/graby/issues/107
No ETA.
