### ISSUE TITLE
HttpClient::fetch returns a binary string

### ISSUE THREAD

**Issue by nicosomb** [j0k3r/graby#137]
When I try to fetch this URL `http://fipcom.net/en.signup`, `HttpClient::fetch` method returns a binary string, see below (the `b` before the content).

<img width="604" alt="capture d ecran 2017-12-04 a 13 28 42" src="https://user-images.githubusercontent.com/121870/33552966-1496ab18-d8f7-11e7-9764-217aeed84813.png">

I don't know why we have this binary string here. It seems to be due to PHP 6 :trollface:  https://stackoverflow.com/questions/4749442/what-does-the-b-in-front-of-string-literals-do

**Comment by j0k3r** [comment]
Which version of PHP? Are you using the latest release?

Using the 1.12.0 on PHP 5.6.31 everything works fine:

```
array(12) {
  'status' =>
  int(200)
  'title' =>
  string(10) "Plain text"
  'language' =>
  string(0) ""
  'date' =>
  NULL
  'authors' =>
  array(0) {
  }
  'html' =>
  string(28511) "<pre>&lt;!DOCTYPE html&gt;

  
    
    
    
	 	<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="" />    
    FIPCOM 2014, Fujairah international photojournalism competition
     
    

       
       
    <link rel="stylesheet" href="css/bootstrap.css" />
	<link rel="stylesheet" href="css/style.css" />
 	<link rel="stylesheet" href="css/bootstrap-responsive.css" />
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.21/themes/ui-lightness/jquery-ui.css" />
    <link href="css"...
  'url' =>
  string(27) "http://fipcom.net/en.signup"
  'content_type' =>
  string(10) "text/plain"
  'open_graph' =>
  array(0) {
  }
  'native_ad' =>
  bool(false)
  'all_headers' =>
  array(0) {
  }
  'summary' =>
  string(0) ""
}
```

**Comment by nicosomb** [comment]
`PHP 7.0.26-1` on wallabag.it.
`PHP 7.1.7` locally.

**Comment by aaa2000** [comment]
Because it is the behaviour of `symfony/var-dumper` https://symfony.com/doc/3.3/components/var_dumper.html#dump-examples-and-output, the html body should not be UTF-8 valid

```
$var = "This is a multi-line string.\n";
$var .= "Hovering a string shows its length.\n";
$var .= "The length of UTF-8 strings is counted in terms of UTF-8 characters.\n";
$var .= "Non-UTF-8 strings length are counted in octet size.\n";
$var .= "Because of this `\xE9` octet (\\xE9),\n";
$var .= "this string is not UTF-8 valid, thus the `b` prefix.\n";
dump($var);
```
