### ISSUE TITLE
Switch to newer HTMLawed

### ISSUE THREAD

**Issue by jtojnar** [j0k3r/graby#138]
`htmlawed/htmlawed` composer package is not compatible with PHP 7.2 and the package maintainer is not responsive. Since PHP 7.2 was released, I [forked the package](https://packagist.org/packages/fossar/htmlawed). I can make you a repo co-owner, if you wish.

**Comment by j0k3r** [comment]
Good idea. Ok for the co-owner (even if I found the code very ugly and almost unmaintainable ...).
Feel free to open a PR to update composer to use your fork :+1: 
Also, maybe you should add 7.2 (and maybe allowed it to fail) in the .travis.yml file to test graby against that version of PHP

**Comment by jtojnar** [comment]
The issue with HTMLawed is that it is not developed publicly, the GitHub repositories basically just copy the files from upstream and publish them on Composer.

I also added you as a maintainer, though not sure if I managed to set the permissions correctly.

**Comment by j0k3r** [comment]
So you just updated the code from that private repository and didn't fix any issue on your own?
I thought you did all changes on your own in that PR https://github.com/kesar/HTMLawed/pull/16 :sweat_smile:

**Comment by jtojnar** [comment]
We might try to convince upstream to release an official composer package. This is more of a mid-term measure.

**Comment by jtojnar** [comment]
We might try to convince upstream to release an official composer package. This is more of a mid-term measure for PHP 7.2 compatibility.

**Comment by j0k3r** [comment]
Posted http://www.bioinformatics.org/phplabware/forum/viewtopic.php?pid=904
We'll see ...

**Comment by j0k3r** [comment]
http://www.bioinformatics.org/phplabware/forum/viewtopic.php?pid=907#p907 :disappointed:

**Comment by aaa2000** [comment]
> I have looked into Packagist, and you are right that it appears unusable if source code is not on GitHub but on a self-hosted site.

it does not need to be hosted on github, it can be a VCS repository https://getcomposer.org/doc/05-repositories.md

**Comment by j0k3r** [comment]
@aaa2000 you're right, maybe you can post a reply to the thread so it'll see that more people are engaged into that composer package

**Comment by Zegnat** [comment]
Just ran into this and have written about [an alternative solution on the Bioinformatics forum](http://www.bioinformatics.org/phplabware/forum/viewtopic.php?id=325).

**Comment by j0k3r** [comment]
I've chosen to use @jtojnar solution.
The one from Bioinformatics looks too complex.
Release in 1.12.1.
