### ISSUE TITLE
Can't install with composer...

### ISSUE THREAD

**Issue by FlashT** [j0k3r/graby#147]
When I do:

php composer.phar install, everything works fine... but there is no Graby itself in Vendor after that operation... only some other things connected to the project...

When after that I do:

php composer.phar require

I am getting an error:

```
Resolving dependencies through SAT
Dependency resolution completed in 6.614 seconds
Reading /home/user/.composer/cache/repo/https---packagist.org/provider-j0k3r$graby.json from cache
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package j0k3r/graby No version set (parsed as 1.0.0) is satisfiable by j0k3r/graby[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by j0k3r** [comment]
What are you trying to do:
- Installing graby as a standalone library to test it?
- Including graby in an existant project?

**Comment by FlashT** [comment]
Standalone ...

**Comment by j0k3r** [comment]
When installing as a standalone, in the vendor dir you won't have graby but its dependencies.
If you want to install it as a standalone, don't user composer to install it, fork the project and git clone it on your machine. Then use `composer` to install graby's deps.

**Comment by j0k3r** [comment]
Great.
Maybe it's not related to graby but it can be related to https://github.com/j0k3r/php-readability too.
