### ISSUE TITLE
Missing Accept header causes problems on some sites

### ISSUE THREAD

**Issue by nijel** [j0k3r/graby#155]
Graby fails to fetch content from https://www.marigold.cz/item/projektovy-manazer-je-v-cesku-sproste-slovo-ke-skode-projektu. The reason is that server fails with HTTP 403 when Accept header is missing.

I've discovered this in Wallabag, but I think Graby might be place to address this (or SafeCurl). All what is needed is to add `Accept: */*` header to performed requests.

I've hacked this into SafeCurl (see https://github.com/j0k3r/safecurl/pull/4), but I'm not really sure this is good location for such fix.

**Comment by j0k3r** [comment]
See https://github.com/j0k3r/safecurl/pull/5
