### ISSUE TITLE
Error using "standalone" graby

### ISSUE THREAD

**Issue by techexo** [j0k3r/graby#177]
Hello everyone,

I have some trouble using a standalone graby configuration, as mentioned here: https://github.com/wallabag/wallabag/issues/3773

I cloned j0k3r/graby, launched `composer require j0k3r/graby dev-master` (wouldn't work without `dev-master` for unknown reason) and created a `fetcher.php` file:

```php
<?php

require 'vendor/autoload.php';

use Graby\Graby;

$article = 'https://www.lemonde.fr/societe/article/2018/11/16/affaire-gregory-la-garde-a-vue-de-murielle-bolle-en-1984-jugee-inconstitutionnelle_5384270_3224.html';

$graby = new Graby(['debug' => true]);
$result = $graby->fetchContent($article);

var_export($result);
```

Graby is working well as far as I can see, but an error with php-readability is triggered:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Readability\mb_regex_encoding() in /d/Eloi/Git/github/graby/vendor/j0k3r/php-readability/src/Readability.php:254
Stack trace:
#0 /d/Eloi/Git/github/graby/vendor/j0k3r/php-readability/src/Readability.php(185): Readability\Readability->loadHtml()
#1 /d/Eloi/Git/github/graby/src/Extractor/ContentExtractor.php(979): Readability\Readability->__construct('        <!DOCTY...', 'https://www.lem...', 'libxml', true)
#2 /d/Eloi/Git/github/graby/src/Extractor/ContentExtractor.php(208): Graby\Extractor\ContentExtractor->getReadability('        <!DOCTY...', 'https://www.lem...', 'libxml', true)
#3 /d/Eloi/Git/github/graby/src/Graby.php(294): Graby\Extractor\ContentExtractor->process('        <!DOCTY...', 'https://www.lem...')
#4 /d/Eloi/Git/github/graby/src/Graby.php(143): Graby\Graby->doFetchContent('https://www.lem...')
#5 /d/Eloi/Git/github/graby/fetcher.php(10): Graby\Graby->fetchContent('https://www.lem...')
#6 {main}
  thrown in /d/Eloi/Git/github/graby/vendor/j0k3r/php-readability/src/Readability.php on line 254
```
and the last instruction in graby's log is:
```
[2018-11-16 15:16:10] graby.DEBUG: Attempting to parse HTML with {parser} {"parser":"libxml"} []
```

Sorry if it is trivial, I am really not used working with PHP, composer and such... :)

**Comment by j0k3r** [comment]
You should use instead `composer install` instead of `composer require` which should only be used when you want to integrate it in an existing project.

**Comment by techexo** [comment]
Ouuuups... I cloned again, did `composer install` but I still have the same error.
In the file Readability.php, the error seems to be thrown by the following lines: https://github.com/j0k3r/php-readability/blob/ed3393a79fe8fbbf1abe7daf17a47b21d862ddfb/src/Readability.php#L253-L255

**Comment by techexo** [comment]
Indeed it works after installing mbstring. I use php7.2 on Debian Jessie, but it is the version Windows Linux Subsystem so it can be buggy...

**Comment by Lucas-C** [comment]
For the record, I also had the same issue today,
and the solution for me was `apt install php-mbstring`.

Thank you @techexo for reporting your problem there and listing your solution 👍
