### ISSUE TITLE
Ignore SSL certificate problems

### ISSUE THREAD

**Issue by aicioara** [j0k3r/graby#197]
Hello! Thank you for this amazing library!

Some links have SSL issues due to some missing root CAs on my system. On cURL, I would supply `-k` (or `--insecure`) to skip the error. Is such an option available in graby?

From the logs:

> [2019-02-13 13:07:37] graby.WARNING: Request throw exception (with no response): {error_message} {"error_message":"cURL Error: SSL certificate problem: unable to get local issuer certificate"} []

**Comment by j0k3r** [comment]
There is no such options at the moment.
But hacking into the code, you can change that line:
https://github.com/j0k3r/graby/blob/master/src/Graby.php#L109

```diff
-           $client ?: new Client(['handler' => new SafeCurlHandler(), 'defaults' => ['cookies' => true]]),
+           $client ?: new Client(['handler' => new SafeCurlHandler(), 'defaults' => ['cookies' => true, 'verify' => false]]),
```

**Comment by jtojnar** [comment]
👎 on  providing option that intentionally breaks security.

**Comment by aicioara** [comment]
Thank you for your help! I really appreciate!
