### ISSUE TITLE
Invalid Cookie value

### ISSUE THREAD

**Issue by Chouchen** [j0k3r/graby#236]
Overall, Graby works well for me but I stumbled upon an error when trying to retrieve [this url](https://twitter.com/BeautifulLoser_/status/1280545391398793223)  (yes, I know 🙄) : 

> (InvalidArgumentException(code: 0): The cookie value \"\"v1_W5t3W8Qs+ktgsdUWgaJeyQ==\"\" contains invalid characters. at /var/www/app/vendor/php-http/message/src/Cookie.php:465)

**Comment by j0k3r** [comment]
Looks like an issue on Twitter side, got the same issue `The cookie value ""v1_SChw6VkjZGnbMqxwcS0jGg=="" contains invalid characters.` 😒

**Comment by j0k3r** [comment]
Found a workaround by giving a wrong `personalization_id ` cookie and it's working!

**Comment by j0k3r** [comment]
I don't know if it's the best way to handle it..
