### ISSUE TITLE
 Uncaught InvalidArgumentException: The cookie value """" contains invalid characters.

### ISSUE THREAD

**Issue by hwiorn** [j0k3r/graby#265]
Similar to #236

I am trying to make brunch.co.kr.txt. I tested `https://brunch.co.kr/@brandonpark/4`.

The HTTP response cookie is
```
Set-Cookie: lwm=""; Domain=brunch.co.kr; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
```

I couldn't retrieve HTML data using the `Cookie` workaround until I added `"` into validateValue regex expression of Cookie(`vendor/php-http/message/src/Cookie.php`).

```
http_header(Cookie): lwm=1; bid=1
```

How can I get the site article properly?

**Comment by j0k3r** [comment]
Finally I copy/pasted the Cookie plugin and reject cookie which aren't valid instead. So there is no more exception thrown in that case.
It should work fine now.
