### ISSUE TITLE
Usage with MAMP PHP

### ISSUE THREAD

**Issue by kingozorg** [j0k3r/graby#295]
My mac only has php 7.1 installed - but i use MAMP with 7.4 or 8!

So composer won't install:
[InvalidArgumentException]                                                   
  Package php-http/guzzle7-adapter has requirements incompatible with your PH  
  P version, PHP extensions and Composer version:                              
    - php-http/guzzle7-adapter 1.0.0 requires php ^7.2 | ^8.0 which does not   
  match your installed version 7.1.33. 

Any work around for this?

**Comment by j0k3r** [comment]
It means you PHP version used is the one from your Mac instead of the one from MAMP.
Maybe your MAMP installation isn't properly installed or configured.
