### ISSUE TITLE
Uncaught PHP Exception Exception: Url is not valid

### ISSUE THREAD

**Issue by Strubbl** [j0k3r/graby#44]
Hi,

in wallabag v2.0.0. i see the following error on importing a json file:

`[2016-04-06 23:52:33] request.CRITICAL: Uncaught PHP Exception Exception: "Url "http://www.pro-linux.de/news/1/23430/linus-torvalds-über-das-internet-der-dinge.html" is not valid." at wallabag/vendor/j0k3r/graby/src/Graby.php line 388 {"exception":"[object] (Exception(code: 0): Url \"http://www.pro-linux.de/news/1/23430/linus-torvalds-über-das-internet-der-dinge.html\" is not valid. at wallabag/vendor/j0k3r/graby/src/Graby.php:388)"} []`

I have no idea why this url is not valid. Maybe you have?

edit: maybe because of the umlauts "ü"?

**Comment by j0k3r** [comment]
Hum maybe, we do that:

```php
if (false === filter_var($url, FILTER_VALIDATE_URL)) {
    throw new \Exception(sprintf('Url "%s" is not valid.', $url));
}
```

I'll check that.
Thanks for reporting

**Comment by Strubbl** [comment]
Yes, documentation for FILTER_VALIDATE_URL says:

> Note that the function will only find ASCII URLs to be valid; internationalized domain names (containing non-ASCII characters) will fail.

https://secure.php.net/manual/en/filter.filters.validate.php

**Comment by j0k3r** [comment]
So that too and it's really sad I'll have to build my own url validate ... :confused:

**Comment by Strubbl** [comment]
If we want to support such things, yes.

Mathias wrote about URL regexes: In search of the perfect URL validation regex https://mathiasbynens.be/demo/url-regex It's complicated. Maybe anybody else has an idea how to validate input URLs
