### ISSUE TITLE
Try to use Google AMP pages for fetching and/or redirect to original page

### ISSUE THREAD

**Issue by tcitworld** [j0k3r/graby#50]
See https://support.google.com/webmasters/answer/6340290?hl=fr

If page meta contains <link rel="amphtml" href="https://www.example.com/url/to/amp-version.html" />, maybe try to parse this one instead of original one.
Same goes to opening original url (quite interesting when you're on mobile).

Of course, this should be set as a setting.

Originally at  https://github.com/wallabag/wallabag/issues/2173

**Comment by j0k3r** [comment]
Well we need to see if it's really a good solution.
It's interesting for getting the content text, for sure. But embedded document might be lost, for example, Twitter embed are displayed like :

```
<amp-twitter data-tweetid="757175117852004353" layout="fixed-height" height="400"></amp-twitter>
```

And they are cleaned later because tags are invalid.
