### ISSUE TITLE
Handle referer from siteconfig

### ISSUE THREAD

**Issue by j0k3r** [j0k3r/graby#62]
When #61 will be merged, we should add the `referer` support for http header since some website can have them configured:

https://github.com/fivefilters/ftr-site-config/blob/5aa171b1b3cff4c5c7a0b3f27803feab2330c1d7/feeds.feedblitz.com.txt

```
http_header(referer): http://feedblitz.com
```

**Comment by Kdecherf** [comment]
I will take a look ;-)
